### ISSUE TITLE
Important Styling

### ISSUE THREAD

**Issue by RyanBeiden** [RyanBeiden/tamagotchi#4]
# User Story

# AC

# Dev Notes
_**Make sure you can't condense this `css` with `sass` functions or mixins before copy and pasting.**_

This will give a start to the Tomagatchi shaped layout:
```css
body {
  background-color: #e8e7e4;
}

.test {
  width: 350px;
  background-color: #FF76DA;
  border: 2px solid #FF76DA;
  border-bottom-left-radius: 0em;
  border-top-left-radius: 20em;
}

.test-2 {
  width: 350px;
  background-color: #719CFF;
  border: 2px solid #719CFF;
  border-bottom-right-radius: 0em;
  border-top-right-radius: 20em;
}

.test-3 {
  width: 350px;
  background-color: #FFE972;
  border: 2px solid #FFE972;
  border-bottom-left-radius: 20em;
  border-top-left-radius: 0em;
  margin-left: 105px;
}

.test-4 {
  width: 350px;
  background-color: #8BFF8F;
  border: 2px solid #8BFF8F;
  border-bottom-right-radius: 20em;
  border-top-right-radius: 0em;
  margin-right: 105px;
}

.container {
  display: flex;
  justify-content: center;
  flex-direction: row;
  flex-wrap: wrap;
  width: 100%;
  align-items: flex-end;
}

/* For header letter color changes while hovering */

.pink {
  color: #707070;
  font-size: 50px;
}

.blue {
  color: #707070;
  font-size: 50px;
}

.yellow {
  color: #707070;
  font-size: 50px;
}

.green {
  color: #707070;
  font-size: 50px;
}

.pink:hover {
  color: #FF76DA;
  cursor: default;
  transition: ease-in 50ms;
}

.blue:hover {
  color: #719CFF;
  cursor: default;
  transition: ease-in 50ms;
}

.yellow:hover {
  color: #FFE972;
  cursor: default;
  transition: ease-in 50ms;
}

.green:hover {
  color: #8BFF8F;
  cursor: default;
  transition: ease-in 50ms;
}

@media only screen and (max-width: 990px) {
  .container {
    display: block;
  }

  .test {
    margin-top: 50px;
    border-radius: 1em;
    width: auto;
  }

  .test-2 {
    margin-top: 50px;
    border-radius: 1em;
    width: auto;
  }

  .test-3 {
    margin-top: 50px;
    border-radius: 1em;
    width: auto;
    margin-left: 0px;
  }

  .test-4 {
    margin-top: 50px;
    border-radius: 1em;
    width: auto;
    margin-right: 0px;
    margin-bottom: 50px;
  }
}
```
